language: java
sudo: true

jdk:
  - openjdk8
  - oraclejdk8

notifications:
  email: false

git:
  depth: 1

branches:
  only:
    - master

before_install:
  - export TZ=Asia/Shanghai

script:
  - mvn clean package -Dmaven.javadoc.skip=true -Dmaven.test.skip=true

after_success:
  -

after_failure:
 -

services:

addons:
  hosts:
  - hasor.net
  - www.hasor.net